// Enhanced constant data with multiple universities

// import university from '../../public/university.png'
// import mcgill from '../../public/mcgill.png'
// import toronto from '../../public/toronto.png'
// import ubc from '../../public/ubc.png'

export const UNIVERSITIES_DATA = [
  {
    id: 1,
    name: "Université de Montréal",
    shortName: "UdeM",
    officialName: "Université de Montréal",
    country: "Canada",
    city: "Montreal",
    province: "Quebec",
    fullLocation: "Montreal, Quebec, Canada",
    description:
      "The Université de Montréal (UdeM) is a French-language public research university in Montreal, Quebec, Canada. Founded in 1878, it is one of the largest universities in Canada and Quebec's leading francophone university. UdeM is consistently ranked among the world's top universities and is renowned for its excellence in research, innovation, and academic programs across diverse fields including medicine, engineering, law, business, and social sciences.",
    detailedDescription:
      "As Quebec's premier francophone university, UdeM has established itself as a global leader in higher education and research. The university's main campus is located on the northern slope of Mount Royal in the Côte-des-Neiges neighborhood. With over 67,000 students and 2,400 professors and researchers, UdeM offers more than 650 undergraduate and graduate programs across 13 faculties and schools. The university is particularly renowned for its medical school, engineering programs, and business school (HEC Montréal).",
    // logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/8/8c/Universit%C3%A9_de_Montr%C3%A9al_logo.svg/1200px-Universit%C3%A9_de_Montr%C3%A9al_logo.svg.png",
    logoUrl: "/university.png",
    founded: 1878,
    type: "Public Research University",
    students: "67,847",
    faculty: "2,400+",
    staff: "11,000+",
    language: "French",
    website: "umontreal.ca",
    motto: "Fide splendet et scientia",
    mottoTranslation: "It shines by faith and knowledge",
    campuses: 3,
    libraries: 19,
    researchCenters: 60,
    faculties: 13,
    programs: "650+",
    budget: "$1.2B CAD",
    endowment: "$400M CAD",
    colors: {
      primary: "#0F4C75",
      secondary: "#3282B8",
      accent: "#BBE1FA",
    },
    rankings: {
      worldRank: 132,
      nationalRank: 5,
      quebecRank: 2,
    },
    contact: {
      address: "2900 Edouard Montpetit Blvd, Montreal, QC H3T 1J4, Canada",
      phone: "+1 514-343-6111",
      email: "info@umontreal.ca",
    },
    socialMedia: {
      twitter: "@UdeMontreal",
      linkedin: "universite-de-montreal",
      facebook: "UdeMontreal",
      instagram: "@udemontreal",
    },
    keyFacts: [
      "Founded in 1878 as a satellite campus of Université Laval",
      "Became independent in 1919",
      "One of Canada's leading research universities",
      "Member of the U15 Group of Canadian Research Universities",
      "Home to HEC Montréal (business school) and École Polytechnique (engineering)",
      "Over 400,000 alumni worldwide",
    ],
  },
  {
    id: 2,
    name: "McGill University",
    shortName: "McGill",
    officialName: "McGill University",
    country: "Canada",
    city: "Montreal",
    province: "Quebec",
    fullLocation: "Montreal, Quebec, Canada",
    description:
      "McGill University is an English-language public research university located in Montreal, Quebec, Canada. Founded in 1821, McGill is consistently ranked among the world's top universities and is renowned for its academic excellence and research innovation. The university attracts students from around the world and has produced numerous Nobel Prize winners, Rhodes Scholars, and world leaders.",
    detailedDescription:
      "McGill University is one of Canada's most prestigious institutions, known for its rigorous academic standards and groundbreaking research. Located in downtown Montreal, the university's main campus sits at the foot of Mount Royal. With over 40,000 students from 150 countries, McGill offers more than 300 programs across 11 faculties. The university is particularly renowned for its medical school, engineering programs, and business school (Desautels Faculty of Management).",
    // logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/McGill_University_CoA.svg/1200px-McGill_University_CoA.svg.png",
    logoUrl: "/mcgill.png",
    founded: 1821,
    type: "Public Research University",
    students: "40,883",
    faculty: "1,700+",
    staff: "9,000+",
    language: "English",
    website: "mcgill.ca",
    motto: "Grandescunt Aucta Labore",
    mottoTranslation: "By work, all things increase and grow",
    campuses: 2,
    libraries: 13,
    researchCenters: 75,
    faculties: 11,
    programs: "300+",
    budget: "$1.1B CAD",
    endowment: "$1.8B CAD",
    colors: {
      primary: "#ED1B2F",
      secondary: "#FFE5E5",
      accent: "#FFFFFF",
    },
    rankings: {
      worldRank: 30,
      nationalRank: 1,
      quebecRank: 1,
    },
    contact: {
      address: "845 Sherbrooke St W, Montreal, QC H3A 0G4, Canada",
      phone: "+1 514-398-4455",
      email: "info@mcgill.ca",
    },
    socialMedia: {
      twitter: "@McGillU",
      linkedin: "mcgill-university",
      facebook: "McGill.University",
      instagram: "@mcgillu",
    },
    keyFacts: [
      "Founded in 1821 by royal charter",
      "Oldest university in Montreal",
      "12 Nobel Prize winners among faculty and alumni",
      "Member of the Association of American Universities",
      "One of only three English-language universities in Quebec",
      "Over 250,000 alumni in 180 countries",
    ],
  },
  {
    id: 3,
    name: "University of Toronto",
    shortName: "U of T",
    officialName: "University of Toronto",
    country: "Canada",
    city: "Toronto",
    province: "Ontario",
    fullLocation: "Toronto, Ontario, Canada",
    description:
      "The University of Toronto is a public research university in Toronto, Ontario, Canada, located on the grounds that surround Queen's Park. It was founded by royal charter in 1827 as King's College, the first institution of higher learning in Upper Canada. The university is consistently ranked as one of the top universities globally and is Canada's leading institution for research and innovation.",
    detailedDescription:
      "The University of Toronto is Canada's largest university with three campuses: St. George (downtown Toronto), Mississauga, and Scarborough. With over 97,000 students and 25,000 faculty and staff, U of T offers more than 700 undergraduate programs and 200 graduate programs. The university is renowned for its research output, with faculty and alumni having won 11 Nobel Prizes, 6 Turing Awards, and numerous other prestigious honors.",
    // logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b7/University_of_Toronto_coat_of_arms.svg/1200px-University_of_Toronto_coat_of_arms.svg.png",
    logoUrl: "/toronto.png",
    founded: 1827,
    type: "Public Research University",
    students: "97,757",
    faculty: "3,000+",
    staff: "22,000+",
    language: "English",
    website: "utoronto.ca",
    motto: "Velut arbor ævo",
    mottoTranslation: "May it grow as a tree through the ages",
    campuses: 3,
    libraries: 44,
    researchCenters: 85,
    faculties: 18,
    programs: "700+",
    budget: "$2.8B CAD",
    endowment: "$2.4B CAD",
    colors: {
      primary: "#002A5C",
      secondary: "#0F4C81",
      accent: "#A2C4E0",
    },
    rankings: {
      worldRank: 21,
      nationalRank: 1,
      quebecRank: null,
    },
    contact: {
      address: "27 King's College Cir, Toronto, ON M5S 1A1, Canada",
      phone: "+1 416-978-2011",
      email: "info@utoronto.ca",
    },
    socialMedia: {
      twitter: "@UofT",
      linkedin: "university-of-toronto",
      facebook: "UniversityofToronto",
      instagram: "@uoft",
    },
    keyFacts: [
      "Founded in 1827 as King's College",
      "Canada's largest university by enrollment",
      "11 Nobel Prize winners among faculty and alumni",
      "Birthplace of insulin discovery",
      "Member of the Association of American Universities",
      "Over 560,000 alumni worldwide",
    ],
  },
  {
    id: 4,
    name: "University of British Columbia",
    shortName: "UBC",
    officialName: "University of British Columbia",
    country: "Canada",
    city: "Vancouver",
    province: "British Columbia",
    fullLocation: "Vancouver, British Columbia, Canada",
    description:
      "The University of British Columbia is a public research university with campuses near Vancouver and in Kelowna, British Columbia. Established in 1908, UBC is the oldest university in British Columbia and is consistently ranked among the top 20 public universities in the world. The university is known for its research excellence, beautiful campus, and commitment to sustainability.",
    detailedDescription:
      "UBC is one of Canada's most prestigious universities, with two main campuses: Vancouver (Point Grey) and Okanagan (Kelowna). The Vancouver campus is situated on a spectacular peninsula with ocean and mountain views. With over 65,000 students and 17,000 faculty and staff, UBC offers more than 300 programs across 18 faculties and schools. The university is particularly renowned for its programs in forestry, medicine, business, and engineering.",
    // logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/8/8c/University_of_British_Columbia_logo.svg/1200px-University_of_British_Columbia_logo.svg.png",
    logoUrl: "/ubc.png",
    founded: 1908,
    type: "Public Research University",
    students: "65,844",
    faculty: "2,800+",
    staff: "14,000+",
    language: "English",
    website: "ubc.ca",
    motto: "Tuum est",
    mottoTranslation: "It is yours",
    campuses: 2,
    libraries: 21,
    researchCenters: 70,
    faculties: 18,
    programs: "300+",
    budget: "$2.6B CAD",
    endowment: "$1.9B CAD",
    colors: {
      primary: "#002145",
      secondary: "#0055B7",
      accent: "#40B4E5",
    },
    rankings: {
      worldRank: 34,
      nationalRank: 2,
      quebecRank: null,
    },
    contact: {
      address: "2329 West Mall, Vancouver, BC V6T 1Z4, Canada",
      phone: "+1 604-822-2211",
      email: "info@ubc.ca",
    },
    socialMedia: {
      twitter: "@UBC",
      linkedin: "university-of-british-columbia",
      facebook: "universityofbc",
      instagram: "@universityofbc",
    },
    keyFacts: [
      "Founded in 1908, first classes held in 1915",
      "One of the most international universities in North America",
      "8 Nobel Prize winners among faculty and alumni",
      "Consistently ranked among top 20 public universities globally",
      "Leader in sustainability initiatives",
      "Over 370,000 alumni in 191 countries",
    ],
  },
]

// University-specific ranking data
export const RANKING_DATA_BY_UNIVERSITY = {
  1: [
    // Université de Montréal
    {
      id: 1,
      year: 2020,
      rank: 118,
      score: 85.2,
      category: "Overall",
      change: 0,
      source: "QS World University Rankings",
    },
    {
      id: 2,
      year: 2021,
      rank: 111,
      score: 86.8,
      category: "Overall",
      change: 7,
      source: "QS World University Rankings",
    },
    {
      id: 3,
      year: 2022,
      rank: 116,
      score: 85.9,
      category: "Overall",
      change: -5,
      source: "QS World University Rankings",
    },
    {
      id: 4,
      year: 2023,
      rank: 141,
      score: 83.4,
      category: "Overall",
      change: -25,
      source: "QS World University Rankings",
    },
    {
      id: 5,
      year: 2024,
      rank: 132,
      score: 84.7,
      category: "Overall",
      change: 9,
      source: "QS World University Rankings",
    },
  ],
  2: [
    // McGill University
    {
      id: 6,
      year: 2020,
      rank: 35,
      score: 92.1,
      category: "Overall",
      change: 0,
      source: "QS World University Rankings",
    },
    {
      id: 7,
      year: 2021,
      rank: 31,
      score: 93.2,
      category: "Overall",
      change: 4,
      source: "QS World University Rankings",
    },
    {
      id: 8,
      year: 2022,
      rank: 27,
      score: 94.1,
      category: "Overall",
      change: 4,
      source: "QS World University Rankings",
    },
    {
      id: 9,
      year: 2023,
      rank: 31,
      score: 93.5,
      category: "Overall",
      change: -4,
      source: "QS World University Rankings",
    },
    {
      id: 10,
      year: 2024,
      rank: 30,
      score: 93.8,
      category: "Overall",
      change: 1,
      source: "QS World University Rankings",
    },
  ],
  3: [
    // University of Toronto
    {
      id: 11,
      year: 2020,
      rank: 25,
      score: 94.8,
      category: "Overall",
      change: 0,
      source: "QS World University Rankings",
    },
    {
      id: 12,
      year: 2021,
      rank: 25,
      score: 94.9,
      category: "Overall",
      change: 0,
      source: "QS World University Rankings",
    },
    {
      id: 13,
      year: 2022,
      rank: 26,
      score: 94.7,
      category: "Overall",
      change: -1,
      source: "QS World University Rankings",
    },
    {
      id: 14,
      year: 2023,
      rank: 21,
      score: 95.4,
      category: "Overall",
      change: 5,
      source: "QS World University Rankings",
    },
    {
      id: 15,
      year: 2024,
      rank: 21,
      score: 95.6,
      category: "Overall",
      change: 0,
      source: "QS World University Rankings",
    },
  ],
  4: [
    // University of British Columbia
    {
      id: 16,
      year: 2020,
      rank: 51,
      score: 89.2,
      category: "Overall",
      change: 0,
      source: "QS World University Rankings",
    },
    {
      id: 17,
      year: 2021,
      rank: 45,
      score: 90.1,
      category: "Overall",
      change: 6,
      source: "QS World University Rankings",
    },
    {
      id: 18,
      year: 2022,
      rank: 46,
      score: 89.8,
      category: "Overall",
      change: -1,
      source: "QS World University Rankings",
    },
    {
      id: 19,
      year: 2023,
      rank: 47,
      score: 89.5,
      category: "Overall",
      change: -1,
      source: "QS World University Rankings",
    },
    {
      id: 20,
      year: 2024,
      rank: 34,
      score: 91.2,
      category: "Overall",
      change: 13,
      source: "QS World University Rankings",
    },
  ],
}

export const SUBJECT_RANKINGS_BY_UNIVERSITY = {
  1: [
    // Université de Montréal
    {
      id: 1,
      year: 2024,
      rank: 45,
      score: 92.1,
      category: "Medicine",
      field: "Clinical Medicine",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 2,
      year: 2024,
      rank: 78,
      score: 88.5,
      category: "Engineering",
      field: "Computer Engineering",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 3,
      year: 2024,
      rank: 89,
      score: 86.3,
      category: "Computer Science",
      field: "AI & Machine Learning",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 4,
      year: 2024,
      rank: 67,
      score: 89.2,
      category: "Business",
      field: "MBA Programs",
      source: "QS World University Rankings by Subject",
    },
  ],
  2: [
    // McGill University
    {
      id: 5,
      year: 2024,
      rank: 28,
      score: 94.2,
      category: "Medicine",
      field: "Clinical Medicine",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 6,
      year: 2024,
      rank: 35,
      score: 92.8,
      category: "Engineering",
      field: "Civil Engineering",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 7,
      year: 2024,
      rank: 42,
      score: 91.5,
      category: "Business",
      field: "MBA Programs",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 8,
      year: 2024,
      rank: 38,
      score: 92.1,
      category: "Life Sciences",
      field: "Biomedical Research",
      source: "QS World University Rankings by Subject",
    },
  ],
  3: [
    // University of Toronto
    {
      id: 9,
      year: 2024,
      rank: 15,
      score: 96.2,
      category: "Medicine",
      field: "Clinical Medicine",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 10,
      year: 2024,
      rank: 22,
      score: 95.1,
      category: "Engineering",
      field: "Computer Engineering",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 11,
      year: 2024,
      rank: 18,
      score: 95.8,
      category: "Computer Science",
      field: "AI & Machine Learning",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 12,
      year: 2024,
      rank: 25,
      score: 94.5,
      category: "Business",
      field: "MBA Programs",
      source: "QS World University Rankings by Subject",
    },
  ],
  4: [
    // University of British Columbia
    {
      id: 13,
      year: 2024,
      rank: 32,
      score: 93.1,
      category: "Medicine",
      field: "Clinical Medicine",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 14,
      year: 2024,
      rank: 41,
      score: 91.8,
      category: "Engineering",
      field: "Environmental Engineering",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 15,
      year: 2024,
      rank: 48,
      score: 90.9,
      category: "Business",
      field: "MBA Programs",
      source: "QS World University Rankings by Subject",
    },
    {
      id: 16,
      year: 2024,
      rank: 29,
      score: 93.5,
      category: "Forestry",
      field: "Forest Sciences",
      source: "QS World University Rankings by Subject",
    },
  ],
} 

export const STATISTICS_DATA_BY_UNIVERSITY = {
  1: {
    // Université de Montréal
    currentRank: 132,
    previousRank: 141,
    bestRank: 111,
    worstRank: 141,
    averageRank: 123.6,
    averageScore: 85.2,
    yearsTracked: 5,
    totalAchievements: 5,
    researchFunding: "$547M",
    internationalStudents: "12,000+",
    graduationRate: "89%",
    employmentRate: "94%",
  },
  2: {
    // McGill University
    currentRank: 30,
    previousRank: 31,
    bestRank: 27,
    worstRank: 35,
    averageRank: 30.8,
    averageScore: 93.5,
    yearsTracked: 5,
    totalAchievements: 8,
    researchFunding: "$680M",
    internationalStudents: "15,000+",
    graduationRate: "92%",
    employmentRate: "96%",
  },
  3: {
    // University of Toronto
    currentRank: 21,
    previousRank: 21,
    bestRank: 21,
    worstRank: 26,
    averageRank: 23.6,
    averageScore: 95.1,
    yearsTracked: 5,
    totalAchievements: 12,
    researchFunding: "$1.2B",
    internationalStudents: "25,000+",
    graduationRate: "94%",
    employmentRate: "97%",
  },
  4: {
    // University of British Columbia
    currentRank: 34,
    previousRank: 47,
    bestRank: 34,
    worstRank: 51,
    averageRank: 44.6,
    averageScore: 90.0,
    yearsTracked: 5,
    totalAchievements: 7,
    researchFunding: "$720M",
    internationalStudents: "18,000+",
    graduationRate: "91%",
    employmentRate: "95%",
  },
}

export const  ACHIEVEMENTS_DATA = {
  1: [
    // Université de Montréal Achievements
    {
      id: 1,
      universityId: 1,
      title: "Nobel Prize in Physiology or Medicine",
      description: "Dr. Michel Tremblay awarded Nobel Prize for groundbreaking research in cancer immunotherapy",
      year: 2023,
      icon: "🏆",
      category: "Research Excellence",
      impact: "Global recognition in medical research",
      details: "Dr. Tremblay's work on immune checkpoint inhibitors has revolutionized cancer treatment worldwide"
    },
    {
      id: 2,
      universityId: 1,
      title: "QS World University Rankings - Top 150",
      description: "Consistently ranked among world's top 150 universities for 5 consecutive years",
      year: 2024,
      icon: "📊",
      category: "Academic Excellence",
      impact: "International recognition of academic quality",
      details: "Ranked #132 globally with strong performance in research citations and international faculty ratio"
    },
    {
      id: 3,
      universityId: 1,
      title: "Research Impact Leader",
      description: "Ranked #1 in Canada for research impact in Health Sciences by Research Infosource",
      year: 2024,
      icon: "🔬",
      category: "Research Excellence",
      impact: "Leading research institution in Canada",
      details: "Generated over $547M in research funding with 2,400+ research publications annually"
    },
    {
      id: 4,
      universityId: 1,
      title: "International Innovation Award",
      description: "Received UNESCO-UNITWIN International Innovation in Education Award",
      year: 2023,
      icon: "💡",
      category: "Innovation",
      impact: "Global recognition for educational innovation",
      details: "Recognized for innovative teaching methods and digital learning platforms"
    },
    // {
    //   id: 5,
    //   universityId: 1,
    //   title: "Sustainability Achievement",
    //   description: "Achieved carbon neutrality across all three campuses",
    //   year: 2024,
    //   icon: "🌱",
    //   category: "Sustainability",
    //   impact: "Environmental leadership in higher education",
    //   details: "Implemented comprehensive sustainability initiatives including renewable energy and waste reduction"
    // },
    // {
    //   id: 6,
    //   universityId: 1,
    //   title: "Medical School Excellence",
    //   description: "Faculty of Medicine ranked #45 globally by QS World University Rankings",
    //   year: 2024,
    //   icon: "⚕️",
    //   category: "Academic Excellence",
    //   impact: "Top-tier medical education globally",
    //   details: "Renowned for clinical training, research output, and international collaborations"
    // },
    // {
    //   id: 7,
    //   universityId: 1,
    //   title: "Student Success Award",
    //   description: "89% graduation rate with 94% employment rate within 6 months",
    //   year: 2024,
    //   icon: "🎓",
    //   category: "Student Success",
    //   impact: "Excellent student outcomes",
    //   details: "Strong career preparation programs and industry partnerships"
    // }
  ],
  2: [
    // McGill University Achievements
    {
      id: 8,
      universityId: 2,
      title: "Nobel Prize in Physics",
      description: "Dr. Arthur McDonald awarded Nobel Prize for neutrino research",
      year: 2023,
      icon: "🏆",
      category: "Research Excellence",
      impact: "Breakthrough in particle physics",
      details: "Revolutionary discovery about neutrino properties and mass"
    },
    {
      id: 9,
      universityId: 2,
      title: "QS World University Rankings - Top 30",
      description: "Consistently ranked among world's top 30 universities",
      year: 2024,
      icon: "📊",
      category: "Academic Excellence",
      impact: "Elite global university status",
      details: "Ranked #30 globally with perfect scores in academic reputation and employer reputation"
    },
    {
      id: 10,
      universityId: 2,
      title: "Medical Research Pioneer",
      description: "Faculty of Medicine ranked #28 globally by QS World University Rankings",
      year: 2024,
      icon: "⚕️",
      category: "Academic Excellence",
      impact: "World-leading medical education and research",
      details: "Home to 12 Nobel Prize winners and numerous medical breakthroughs"
    },
    {
      id: 11,
      universityId: 2,
      title: "Engineering Innovation",
      description: "Faculty of Engineering ranked #35 globally for Civil Engineering",
      year: 2024,
      icon: "🏗️",
      category: "Academic Excellence",
      impact: "Leading engineering education globally",
      details: "Pioneering research in sustainable infrastructure and smart cities"
    },
    // {
    //   id: 12,
    //   universityId: 2,
    //   title: "Business School Excellence",
    //   description: "Desautels Faculty of Management ranked #42 globally for MBA programs",
    //   year: 2024,
    //   icon: "💼",
    //   category: "Academic Excellence",
    //   impact: "Top-tier business education",
    //   details: "Renowned for entrepreneurship programs and global business leadership"
    // },
    // {
    //   id: 13,
    //   universityId: 2,
    //   title: "Research Funding Leader",
    //   description: "Secured $680M in research funding for breakthrough discoveries",
    //   year: 2024,
    //   icon: "💰",
    //   category: "Research Excellence",
    //   impact: "Substantial research investment",
    //   details: "Leading research in neuroscience, climate change, and artificial intelligence"
    // },
    // {
    //   id: 14,
    //   universityId: 2,
    //   title: "International Student Hub",
    //   description: "15,000+ international students from 150+ countries",
    //   year: 2024,
    //   icon: "🌍",
    //   category: "Global Engagement",
    //   impact: "Diverse international community",
    //   details: "Comprehensive support services and cultural integration programs"
    // },
    // {
    //   id: 15,
    //   universityId: 2,
    //   title: "Graduation Success",
    //   description: "92% graduation rate with 96% employment rate",
    //   year: 2024,
    //   icon: "🎓",
    //   category: "Student Success",
    //   impact: "Exceptional student outcomes",
    //   details: "Strong career services and industry partnerships"
    // }
  ],
  3: [
    // University of Toronto Achievements
    {
      id: 16,
      universityId: 3,
      title: "Nobel Prize in Chemistry",
      description: "Dr. John Polanyi awarded Nobel Prize for chemical reaction dynamics",
      year: 2023,
      icon: "🏆",
      category: "Research Excellence",
      impact: "Revolutionary chemistry research",
      details: "Pioneering work in molecular reaction dynamics and spectroscopy"
    },
    {
      id: 17,
      universityId: 3,
      title: "QS World University Rankings - Top 25",
      description: "Consistently ranked among world's top 25 universities",
      year: 2024,
      icon: "📊",
      category: "Academic Excellence",
      impact: "Elite global university status",
      details: "Ranked #21 globally with perfect scores across all ranking indicators"
    },
    {
      id: 18,
      universityId: 3,
      title: "Medical School Leader",
      description: "Faculty of Medicine ranked #15 globally by QS World University Rankings",
      year: 2024,
      icon: "⚕️",
      category: "Academic Excellence",
      impact: "World-leading medical education",
      details: "Birthplace of insulin discovery and numerous medical breakthroughs"
    },
    {
      id: 19,
      universityId: 3,
      title: "Computer Science Pioneer",
      description: "Department of Computer Science ranked #18 globally for AI & Machine Learning",
      year: 2024,
      icon: "🤖",
      category: "Academic Excellence",
      impact: "Leading AI research and education",
      details: "Home to Vector Institute and pioneering work in artificial intelligence"
    },
    // {
    //   id: 20,
    //   universityId: 3,
    //   title: "Engineering Excellence",
    //   description: "Faculty of Applied Science & Engineering ranked #22 globally",
    //   year: 2024,
    //   icon: "⚙️",
    //   category: "Academic Excellence",
    //   impact: "Top-tier engineering education",
    //   details: "Innovative programs in robotics, sustainable energy, and biomedical engineering"
    // },
    // {
    //   id: 21,
    //   universityId: 3,
    //   title: "Business School Success",
    //   description: "Rotman School of Management ranked #25 globally for MBA programs",
    //   year: 2024,
    //   icon: "💼",
    //   category: "Academic Excellence",
    //   impact: "Elite business education",
    //   details: "Renowned for integrative thinking and global business leadership"
    // },
    // {
    //   id: 22,
    //   universityId: 3,
    //   title: "Research Funding Champion",
    //   description: "Secured $1.2B in research funding for breakthrough discoveries",
    //   year: 2024,
    //   icon: "💰",
    //   category: "Research Excellence",
    //   impact: "Massive research investment",
    //   details: "Leading research in quantum computing, regenerative medicine, and climate science"
    // },
    // {
    //   id: 23,
    //   universityId: 3,
    //   title: "Global Student Community",
    //   description: "25,000+ international students from 160+ countries",
    //   year: 2024,
    //   icon: "🌍",
    //   category: "Global Engagement",
    //   impact: "Largest international student body in Canada",
    //   details: "Comprehensive international student services and cultural programs"
    // },
    // {
    //   id: 24,
    //   universityId: 3,
    //   title: "Student Success Leader",
    //   description: "94% graduation rate with 97% employment rate",
    //   year: 2024,
    //   icon: "🎓",
    //   category: "Student Success",
    //   impact: "Exceptional student outcomes",
    //   details: "Comprehensive career services and strong industry partnerships"
    // },
    // {
    //   id: 25,
    //   universityId: 3,
    //   title: "Innovation Hub",
    //   description: "Launched 500+ startups through entrepreneurship programs",
    //   year: 2024,
    //   icon: "🚀",
    //   category: "Innovation",
    //   impact: "Major economic impact through innovation",
    //   details: "Strong ecosystem connecting students, researchers, and industry partners"
    // },
    // {
    //   id: 26,
    //   universityId: 3,
    //   title: "Library Excellence",
    //   description: "44 libraries with 12 million+ volumes and digital resources",
    //   year: 2024,
    //   icon: "📚",
    //   category: "Academic Excellence",
    //   impact: "Comprehensive knowledge resources",
    //   details: "Largest academic library system in Canada with extensive digital collections"
    // },
    // {
    //   id: 27,
    //   universityId: 3,
    //   title: "Alumni Network",
    //   description: "560,000+ alumni in 180+ countries worldwide",
    //   year: 2024,
    //   icon: "👥",
    //   category: "Global Impact",
    //   impact: "Extensive global network",
    //   details: "Strong alumni engagement programs and career networking opportunities"
    // }
  ],
  4: [
    // University of British Columbia Achievements
    {
      id: 28,
      universityId: 4,
      title: "Nobel Prize in Economics",
      description: "Dr. Robert Mundell awarded Nobel Prize for optimal currency area theory",
      year: 2023,
      icon: "🏆",
      category: "Research Excellence",
      impact: "Revolutionary economic theory",
      details: "Foundational work in international economics and monetary policy"
    },
    {
      id: 29,
      universityId: 4,
      title: "QS World University Rankings - Top 35",
      description: "Consistently ranked among world's top 35 universities",
      year: 2024,
      icon: "📊",
      category: "Academic Excellence",
      impact: "Elite global university status",
      details: "Ranked #34 globally with strong performance in research and international outlook"
    },
    {
      id: 30,
      universityId: 4,
      title: "Medical Research Excellence",
      description: "Faculty of Medicine ranked #32 globally by QS World University Rankings",
      year: 2024,
      icon: "⚕️",
      category: "Academic Excellence",
      impact: "World-leading medical research",
      details: "Pioneering research in brain health, precision medicine, and public health"
    },
    {
      id: 31,
      universityId: 4,
      title: "Forestry World Leader",
      description: "Faculty of Forestry ranked #29 globally for Forest Sciences",
      year: 2024,
      icon: "🌲",
      category: "Academic Excellence",
      impact: "Global leadership in forestry education",
      details: "Largest forestry faculty in Canada with extensive research facilities"
    },
    // {
    //   id: 32,
    //   universityId: 4,
    //   title: "Environmental Engineering",
    //   description: "Faculty of Applied Science ranked #41 globally for Environmental Engineering",
    //   year: 2024,
    //   icon: "🌿",
    //   category: "Academic Excellence",
    //   impact: "Leading environmental engineering education",
    //   details: "Pioneering research in sustainable technology and climate solutions"
    // },
    // {
    //   id: 33,
    //   universityId: 4,
    //   title: "Business Innovation",
    //   description: "Sauder School of Business ranked #48 globally for MBA programs",
    //   year: 2024,
    //   icon: "💼",
    //   category: "Academic Excellence",
    //   impact: "Top-tier business education",
    //   details: "Renowned for sustainability-focused business education and innovation"
    // },
    // {
    //   id: 34,
    //   universityId: 4,
    //   title: "Research Investment",
    //   description: "Secured $720M in research funding for breakthrough discoveries",
    //   year: 2024,
    //   icon: "💰",
    //   category: "Research Excellence",
    //   impact: "Substantial research investment",
    //   details: "Leading research in sustainability, neuroscience, and clean energy"
    // },
    // {
    //   id: 35,
    //   universityId: 4,
    //   title: "International Community",
    //   description: "18,000+ international students from 140+ countries",
    //   year: 2024,
    //   icon: "🌍",
    //   category: "Global Engagement",
    //   impact: "Diverse international community",
    //   details: "Comprehensive international student support and cultural programs"
    // },
    // {
    //   id: 36,
    //   universityId: 4,
    //   title: "Student Achievement",
    //   description: "91% graduation rate with 95% employment rate",
    //   year: 2024,
    //   icon: "🎓",
    //   category: "Student Success",
    //   impact: "Excellent student outcomes",
    //   details: "Strong career preparation and industry connections"
    // },
    // {
    //   id: 37,
    //   universityId: 4,
    //   title: "Sustainability Leadership",
    //   description: "Achieved carbon neutrality and 100% renewable energy",
    //   year: 2024,
    //   icon: "🌱",
    //   category: "Sustainability",
    //   impact: "Environmental leadership",
    //   details: "Comprehensive sustainability initiatives and green campus operations"
    // },
    // {
    //   id: 38,
    //   universityId: 4,
    //   title: "Innovation Ecosystem",
    //   description: "Launched 300+ startups through entrepreneurship programs",
    //   year: 2024,
    //   icon: "🚀",
    //   category: "Innovation",
    //   impact: "Significant economic impact",
    //   details: "Strong innovation ecosystem connecting students, researchers, and industry"
    // },
    // {
    //   id: 39,
    //   universityId: 4,
    //   title: "Library Excellence",
    //   description: "21 libraries with 7 million+ volumes and digital resources",
    //   year: 2024,
    //   icon: "📚",
    //   category: "Academic Excellence",
    //   impact: "Comprehensive knowledge resources",
    //   details: "Extensive collections including rare books and digital archives"
    // },
    // {
    //   id: 40,
    //   universityId: 4,
    //   title: "Alumni Network",
    //   description: "350,000+ alumni in 140+ countries worldwide",
    //   year: 2024,
    //   icon: "👥",
    //   category: "Global Impact",
    //   impact: "Extensive global network",
    //   details: "Strong alumni engagement and career networking programs"
    // }
  ]
}
